# Generated by Django 5.0 on 2023-12-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='category_name',
            new_name='name',
        ),
    ]
