# Generated by Django 4.2.8 on 2023-12-25 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 6, 24, 3, 48726, tzinfo=datetime.timezone.utc)),
        ),
    ]
