# Generated by Django 5.0 on 2023-12-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_category_name_quizmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='author',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
