# Generated by Django 5.0 on 2023-12-26 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizuser_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 5, 19, 43, 641524, tzinfo=datetime.timezone.utc)),
        ),
    ]
