# Generated by Django 4.2.8 on 2023-12-26 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizuser_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 6, 33, 45, 56631, tzinfo=datetime.timezone.utc)),
        ),
    ]
