# Generated by Django 5.0 on 2023-12-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='lang',
            field=models.CharField(default="O'zbek tili", max_length=15),
            preserve_default=False,
        ),
    ]
