# Generated by Django 5.0 on 2024-01-05 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_question_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 5, 23, 46, 462740, tzinfo=datetime.timezone.utc)),
        ),
    ]
