# Generated by Django 5.0 on 2023-12-23 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 6, 55, 42, 207765, tzinfo=datetime.timezone.utc)),
        ),
    ]
