# Generated by Django 5.0 on 2023-12-23 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quizuser_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 6, 56, 30, 163755, tzinfo=datetime.timezone.utc)),
        ),
    ]
